version: '3.3'
services:
# Bancos
  pg-db:
    image: "postgres"
    restart: always
    mem_limit: 1024m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234

  redis:
    image: "redis:alpine"
    container_name: "redis"
    restart: always
    mem_limit: 512m
    ports:
      - "6379:6379"

# ELK
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0-amd64 
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logs

  kibana:
    container_name: kibana
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:7.13.0-amd64
    environment:
      - ELASTICSEARCH_URL="http://localhost:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"   
    networks:
      - logs

# Kafka
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    mem_limit: 512m
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    mem_limit: 512m
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# SonarQube
  sonarqube:
    image: sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://pg-db:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: 1234
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - sonarqube_data:/opt/SonarQube/data
      - sonarqube_extensions:/opt/SonarQube/extensions
      - sonarqube_logs:/opt/SonarQube/logs
    ports:
      - "9000:9000"
    depends_on:
      - pg-db

volumes:
  elasticsearch-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

networks:
  logs:
    driver: bridge